name: flutter_realtime_detection
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  camera: 0.5.7+4
  tflite: 1.1.2
  
flutter:
  uses-material-design: true
  assets:
   - assets/yolov2_tiny.tflite
   - assets/yolov2_tiny.txt
   - assets/ssd_mobilenet.tflite
   - assets/ssd_mobilenet.txt
   - assets/mobilenet_v1_1.0_224.tflite
   - assets/mobilenet_v1_1.0_224.txt
   - assets/posenet_mv1_075_float_from_checkpoints.tflite
